def calculate_payment_plan(due_amount, payment_today):
    # Invalid payment
    if payment_today <= 0:
        return {
            "status": "invalid",
            "message": "Please enter a valid payment amount."
        }

    # Full payment
    if payment_today >= due_amount:
        return {
            "status": "full",
            "payment_today": due_amount,
            "remaining_balance": 0,
            "installments": 0,
            "monthly_installment": 0,
            "message": "Thank you! Your outstanding balance will be paid in full today."
        }

    # Less than minimum allowed
    if payment_today < 50:
        return {
            "status": "rejected",
            "message": (
                "Unfortunately, we cannot accept payments below $50 today."
            )
        }

    remaining = due_amount - payment_today

    # Between $50 and $99.99
    if payment_today < 100:
        monthly = round(remaining/12, 2)
        return {
            "status": "plan12",
            "payment_today": payment_today,
            "remaining_balance": remaining,
            "installments": 12,
            "monthly_installment": monthly,
            "message": (
                f"You can pay ${payment_today:.2f} today.\n\n"
                f"The remaining ${remaining:.2f} "
                f"will be divided into **12 monthly installments** "
                f"of ${monthly:.2f}."
            )
        }

    # $100 or more
    monthly = round(remaining/9, 2)
    return {
        "status": "plan9",
        "payment_today": payment_today,
        "remaining_balance": remaining,
        "installments": 9,
        "monthly_installment": monthly,
        "message": (
            f"You can pay ${payment_today:.2f} today.\n\n"
            f"The remaining ${remaining:.2f} "
            f"will be divided into **9 monthly installments** "
            f"of ${monthly:.2f}."
        )
    }


# this the main business logic, can be generated by llms, but i prefered not to do so